# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx2G
org.gradle.parallel=true

# Fabric Properties
minecraft_version=1.21.1
yarn_mappings=1.21.1+build.3
loader_version=0.16.10

# Mod Properties
mod_version=1.0.0
maven_group=com.timur.wristwatch
archives_base_name=wristwatch

# Dependencies
fabric_version=0.116.17+1.21.1
